version: 2
updates:
  # Python dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  # Frontend dependencies (security update grouped)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # Frontend dependencies (security updates grouped)
  # - package-ecosystem: npm
  #   directory: "/frontend"
  #   schedule:
  #     interval: daily
  #   open-pull-requests-limit: 0

  # Frontend dependencies all updates grouped by major/minor
  # - package-ecosystem: npm
  #   directory: "/frontend" 
  #   schedule:
  #     interval: daily
  #   open-pull-requests-limit: 10
  #   groups:
  #     minor-and-patch:
  #       update-types:
  #         - "minor"
  #         - "patch"

  #     major-updates:
  #       update-types:
  #         - "major"
