version: 2
updates:
  # Python dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  # Frontend dependencies (security update grouped)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    security-updates:
      enabled: true
    groups:
      security-updates:
        patterns:
          - "*" 

  # Frontend dependencies (security updates grouped)
  # - package-ecosystem: npm
  #   directory: "/frontend"
  #   schedule:
  #     interval: daily
  #   open-pull-requests-limit: 0

  # Frontend dependencies all updates grouped by major/minor
  # - package-ecosystem: npm
  #   directory: "/frontend" 
  #   schedule:
  #     interval: daily
  #   open-pull-requests-limit: 10
  #   groups:
  #     minor-and-patch:
  #       update-types:
  #         - "minor"
  #         - "patch"

  #     major-updates:
  #       update-types:
  #         - "major"
