version: 2
updates:
  # Python dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  # Frontend dependencies
  - package-ecosystem: npm
    directory: "/frontend" 
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - "semver:minor"
          - "semver:patch"

      major-updates:
        update-types:
          - "semver:major"
