version: '3.8'

services:

  aiarena-redis:
    image: redis:latest
    container_name: aiarena-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - aiarena-redis-data:/data

  aiarena-db:
    image: postgres:11.18-bullseye
    container_name: aiarena-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/custom_init.sql:/docker-entrypoint-initdb.d/1.sql
      - aiarena-db-data:/var/lib/postgresql/data
  aiarena-web:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../../
    container_name: aiarena-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - aiarena-web-data:/data
      - ../../.:/app
    depends_on:
      - aiarena-redis
      - aiarena-db
    command: >
      sh -c "python /app/manage.py collectstatic --noinput &&
             python /app/manage.py migrate &&
             python /app/manage.py runserver 0.0.0.0:8000"

  aiarena-web-test:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../../
    container_name: aiarena-web-test
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=aiarena-postgres
    volumes:
      - ../../.:/app
    depends_on:
      aiarena-db:
        condition: service_healthy
    command: >
      sh -c "python /app/manage.py test"


volumes:
  aiarena-redis-data:
  aiarena-db-data:
  aiarena-web-data:

networks:
  default:
    name: aiarena-network