version: '3.8'

services:

  aiarena-redis:
    image: redis:latest
    container_name: aiarena-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - aiarena-redis-data:/data

  aiarena-mysql:
    image: mysql:8.0.31
    container_name: aiarena-mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/custom_init.sql:/docker-entrypoint-initdb.d/1.sql
      - aiarena-mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      start_period: 10s

  aiarena-web:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../../
    container_name: aiarena-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - aiarena-web-data:/data
      - ../../.:/app
    depends_on:
      aiarena-redis:
        condition: service_started
      aiarena-mysql:
        condition: service_healthy
    command: >
      sh -c "python /app/manage.py collectstatic --noinput &&
             python /app/manage.py migrate &&
             python /app/manage.py runserver 0.0.0.0:8000"

  aiarena-mysql-test:
    image: mysql:8.0.31
    container_name: aiarena-mysql-test
    restart: unless-stopped
    env_file:
      - .env.test
    expose:
      - "3306"
    volumes:
      - ./mysql/custom_test_init.sql:/docker-entrypoint-initdb.d/1.sql
      - aiarena-mysql-test-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uaiarena", "-paiarena" ]
      timeout: 10s
      retries: 10
      start_period: 10s

  aiarena-web-test:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../../
    container_name: aiarena-web-test
    env_file:
      - .env.test
    environment:
      - MYSQL_DATABASE=aiarena
    volumes:
      - ../../.:/app
    depends_on:
      aiarena-mysql-test:
        condition: service_healthy
    command: >
      sh -c "python /app/manage.py test --noinput"


volumes:
  aiarena-redis-data:
  aiarena-mysql-data:
  aiarena-mysql-test-data:
  aiarena-web-data:

networks:
  default:
    name: aiarena-network