apiVersion: v1
data:
  init.sh: "#!/bin/bash\n\npython manage.py migrate \npython manage.py collectstatic
    --noinput"
kind: ConfigMap
metadata:
  name: aiarena-web-init-script

---

apiVersion: v1
data:
  ucr-app.conf: "upstream app_server {\n      server 127.0.0.1:3000 fail_timeout=0;\n
    \   }\n\n    server {\n      listen 80;\n      client_max_body_size 4G;\n\n      access_log
    /var/log/nginx/access.log combined;\n      error_log  /var/log/nginx/error.log
    warn;\n\n      keepalive_timeout 5;\n\n      # path for static files (only needed
    for serving local staticfiles)\n      root /var/www/html/;\n\n      location /
    {\n      \n\n        location /nghealth {\n          return 200;\n        }\n\n
    \       try_files $uri @proxy_to_app ;\n      }\n\n      location @proxy_to_app
    {\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header
    X-Forwarded-Proto $scheme;\n        proxy_set_header Host $http_host;\n\n        proxy_redirect
    off;\n        proxy_pass http://app_server;\n      }\n\n      error_page 500 502
    503 504 /500.html;\n      location = /500.html {\n        root /var/www/html/;\n
    \     }\n    }"
kind: ConfigMap
metadata:
  name: backend-api-nginx
