apiVersion: v1
kind: Service
metadata:
  name: aiarena-web
  labels:
    app: aiarena-web
spec:
  selector:
    app: aiarena-web
  ports:
  - name: 3000tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: 80tcp
    port: 80
    protocol: TCP
    targetPort: 80