apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiarena-web
spec:
  template:
    spec:
      volumes:
        - name: env-py
          secret:
            secretName: aiarena-web-env-py-staging
        - name: logs
          persistentVolumeClaim:
            $patch: delete
          emptyDir:
            {}
        - emptyDir: { }
          name: postgres
        - configMap:
            defaultMode: 511
            name: db-init-staging
            optional: false
          name: db-init-script
        - emptyDir: { }
          name: media-staging
          persistentVolumeClaim:
            $patch: delete
        - emptyDir: { }
          name: private-media-staging
          persistentVolumeClaim:
            $patch: delete
        - name: postgresql-init-script
          secret:
            defaultMode: 420
            optional: false
            secretName: postgresql-init-script-staging

      initContainers:
        - name: django-init
          volumeMounts:
            - mountPath: /prod_media
              name: media
            - mountPath: /private_media
              name: private-media-staging
            - mountPath: /media
              name: media-staging
            - mountPath: /prod_private_media
              name: private-media
      containers:
        - name: aiarena-web
          args:
            - 'python manage.py migrate && python manage.py purgesensitivedata && gunicorn -b :3000 aiarena.wsgi'
          command:
            - /bin/sh
            - '-c'
          volumeMounts:
            - mountPath: /prod_private_media
              name: private-media
              readOnly: true
            - mountPath: /prod_media
              name: media
              readOnly: true
            - mountPath: /private_media
              name: private-media-staging
              readOnly: true
            - mountPath: /media
              name: media-staging
              readOnly: true
        - envFrom:
            - secretRef:
                name: postgres-pwds-staging
                optional: false
          image: postgres:12.13
          imagePullPolicy: Always
          name: postgres
          ports:
            - containerPort: 5432
              name: 5432tcp
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgres
            - mountPath: /docker-entrypoint-initdb.d/init.sh
              name: db-init-script
              subPath: init.sh
            - mountPath: /docker-entrypoint-initdb.d/1.sql
              name: postgresql-init-script
              subPath: 1.sql





