version: '3.8'

services:

  devcontainer-aiarena-redis:
    image: redis:latest
    container_name: devcontainer-aiarena-redis
    restart: unless-stopped
    ports:
      - 6379:6379

  devcontainer-aiarena-postgres:
    image: postgres:12.13
    container_name: devcontainer-aiarena-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - devcontainer-aiarena-postgres-volume:/var/lib/postgresql/data/
      - ./postgres:/docker-entrypoint-initdb.d

  devcontainer-aiarena-app:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ../
    container_name: devcontainer-aiarena-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - devcontainer-aiarena-redis
      - devcontainer-aiarena-postgres
    volumes:
      - ..:/workspace
    command: sleep infinity

volumes:
  devcontainer-aiarena-postgres-volume: