name: Django CI

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: |
        docker compose -f docker/local/docker-compose.yml up aiarena-web-test --exit-code-from=aiarena-web-test --force-recreate --build
