name: Production Deploy CI

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Production
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: exit
        host: ${{ secrets.PRODUCTION_HOST }}
        port: ${{ secrets.PRODUCTION_PORT }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        privateKey: ${{ secrets.PRODUCTION_KEY }}




