name: Production Deploy CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
        submodules: true

    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1

    - name: Update Image Version in the related Kustomization kustomization.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'kubernetes/overlays/prod/kustomization.yaml'
        propertyPath: 'images.newTag'
        value: ${{ steps.version.outputs.version }}
        branch: build/${{ steps.version.outputs.version }}
        targetBranch: master
        createPR: true
        message: 'Update Image Version to ${{ steps.gitversion.outputs.SemVer }}'

    - uses: imranismail/setup-kustomize@v2
    - run: |
        (cd kubernetes/overlays/prod/ && kustomize edit set image aiarena/aiarena-web=${{ steps.version.outputs.version }})

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'kubernetes/overlays/prod/kustomization.yml'

        # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
        # Default: true
        push: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        - uses: avakar/tag-and-release@v1
          with:
            tag_name: ${{ steps.version.outputs.version }}
            release_name: "Release ${{ steps.gitversion.outputs.SemVer }}"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}









