name: Production Deploy CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: GitHub Action to Setup GitVersion
      # You may pin to the exact commit or the version.
      # uses: StanleyGoldman/setup-gitversion@a374f5e1b8c33fb6efd03c402cb511f02eafa245
      uses: StanleyGoldman/setup-gitversion@v1.0.1
      with:
        # Version range or exact version of GitVersion to use
        gitversion-version: 5.*

    - name: GitVersion action
      # You may pin to the exact commit or the version.
      # uses: nmcc/actions-gitversion@4ab384d333506ede37c82ca3e03f4005b18b7573
      uses: nmcc/actions-gitversion@v1
      with:
        # Path to the gitversion executable
        path-to-gitversion: GitVersion

    - name: Update Image Version in the related Kustomization kustomization.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'kubernetes/overlays/prod/kustomization.yaml'
        propertyPath: 'images.newTag'
        value: ${{ steps.gitversion.outputs.SemVer }}
        branch: build/${{ steps.gitversion.outputs.SemVer }}
        targetBranch: master
        createPR: true
        message: 'Update Image Version to ${{ steps.gitversion.outputs.SemVer }}'

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        - uses: avakar/tag-and-release@v1
          with:
            tag_name: ${{ steps.gitversion.outputs.SemVer }}
            release_name: "Release ${{ steps.gitversion.outputs.SemVer }}"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}









