name: Staging Deploy CI

on:
  push:
    branches: [ "feature/containerization" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
        submodules: true

    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1

    - name: Use the version
      run: |
        echo ${{ steps.version.outputs.version }}
    - name: Build the Docker image
      run: docker build . --build-arg=ENVIRONMENT_TYPE=PRODUCTION --file docker/Dockerfile --tag aiarena/aiarena-web:${{ steps.version.outputs.version }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Upload image
      run: |
        docker push aiarena/aiarena-web:${{ steps.version.outputs.version }}

    - name: Update Image Version in the related Kustomization kustomization.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'kubernetes/overlays/staging/kustomization.yaml'
        propertyPath: 'images.newTag'
        value: ${{ steps.version.outputs.version }}
        branch: build/${{ steps.version.outputs.version }}
        targetBranch: feature/containerization
        createPR: true
        message: 'Update Image Version to ${{ steps.gitversion.outputs.SemVer }}'





