name: Staging Deploy CI

on:
  push:
    branches: [ staging ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Staging
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: exit
        host: ${{ secrets.STAGING_HOST }}
        port: ${{ secrets.STAGING_PORT }}
        username: ${{ secrets.STAGING_USERNAME }}
        privateKey: ${{ secrets.STAGING_KEY }}




