name: Staging Deploy CI

on:
  push:
    branches: [ "feature/containerization" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
        submodules: true

    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1

    - name: Use the version
      run: |
        echo ${{ steps.version.outputs.version }}
    - name: Build the Docker image
      run: docker build . --build-arg=ENVIRONMENT_TYPE=PRODUCTION --file docker/Dockerfile --tag aiarena/aiarena-web:${{ steps.version.outputs.version }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Upload image
      run: |
        docker push aiarena/aiarena-web:${{ steps.version.outputs.version }}

    - name: Kustomize Edit image
      # You may pin to the exact commit or the version.
      # uses: williamhogman/kustomize-set-image-hook@c9f7c8ae7aa5ea6224bc39376e8d300d04757068
      uses: williamhogman/kustomize-set-image-hook@v1.5
      with:
        # The path to the folder containing the kustomization
        kustomizePath: kubernetes/overlays/staging/
        # Name of the image to replace the image
        name: aiarena/aiarena-web
        # The new tag for the named image
        newTag: ${{ steps.version.outputs.version }}
        newName: aiarena/aiarena-web

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        add_paths: kubernetes/overlays/staging/kustomization.yml
        commit-message: "[auto] Bump image tag to ${{ steps.version.outputs.version }}"
        delete-branch: true
        branch: auto/${{ steps.version.outputs.version }}





