name: Staging Deploy CI

on:
  push:
    branches: [ "feature/containerization" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
        submodules: true

    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1

    - name: Use the version
      run: |
        echo ${{ steps.version.outputs.version }}
    - name: Build the Docker image
      run: docker build . --build-arg=ENVIRONMENT_TYPE=PRODUCTION --file docker/Dockerfile --tag aiarena/aiarena-web:${{ steps.version.outputs.version }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Upload image
      run: |
        docker push aiarena/aiarena-web:${{ steps.version.outputs.version }}

    - uses: imranismail/setup-kustomize@v2
    - run: |
        (cd kubernetes/overlays/staging/ && kustomize edit set image aiarena/aiarena-web=:${{ steps.version.outputs.version }})

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'kubernetes/overlays/prod/kustomization.yml'

        # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
        # Default: true
        push: true






